<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MAA-5CG1158Q3P" failures="0" tests="7" name="eero.dogfood.B2B.BusinessNetworkCases" time="2.620" errors="1" timestamp="2024-03-12T16:11:57 IST" skipped="6">
  <testcase classname="eero.dogfood.B2B.BusinessNetworkCases" name="BaseConfig" time="2.620">
    <error message="Index 0 out of bounds for length 0" type="java.lang.IndexOutOfBoundsException">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:359)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at eero.dogfood.eeroos.BaseTest.BaseConfig(BaseTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- BaseConfig -->
  <system-out/>
  <testcase classname="eero.dogfood.B2B.BusinessNetworkCases" name="C28492" time="0.000">
    <skipped/>
  </testcase> <!-- C28492 -->
  <system-out/>
  <testcase classname="eero.dogfood.B2B.BusinessNetworkCases" name="C235445">
    <skipped/>
  </testcase> <!-- C235445 -->
  <system-out/>
  <testcase classname="eero.dogfood.B2B.BusinessNetworkCases" name="C29192">
    <skipped/>
  </testcase> <!-- C29192 -->
  <system-out/>
  <testcase classname="eero.dogfood.B2B.BusinessNetworkCases" name="C23963">
    <skipped/>
  </testcase> <!-- C23963 -->
  <system-out/>
  <testcase classname="eero.dogfood.B2B.BusinessNetworkCases" name="C233647">
    <skipped/>
  </testcase> <!-- C233647 -->
  <system-out/>
  <testcase classname="eero.dogfood.B2B.BusinessNetworkCases" name="C37224">
    <skipped/>
  </testcase> <!-- C37224 -->
  <system-out/>
</testsuite> <!-- eero.dogfood.B2B.BusinessNetworkCases -->
